### PR TITLE
add fltk-form example

### PR DESCRIPTION
**Pull request by 1sra3l**
quick fl2rust + fltk-form example

The only thing I am unsure about is the "dependencies" line I added in the `Cargo.toml`  is that the right way to add them?

### CODE REVIEW

**Comment by MoAlyousef** [comment]
Thanks for the PR. The dependency to fltk-form and fltk-form-derive should be added in the `[dev-dependencies]` since, like fltk, they're only used in the examples.

**Comment by 1sra3l** [comment]
Update the README.md more when you have the link to the source code, and add any information you want.  I put the fltk-form section at the end of the README, feel free to change it!

**Comment by MoAlyousef** [comment]
Looks good 👍

**Comment by 1sra3l** [comment]
Thanks!  I might create more to show a more detailed `emit()`, or how to access ui elements in more detail

**Comment by MoAlyousef** [comment]
Sounds good

**Pull request merged**
